CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tg_id" bigint NOT NULL,
  "username" varchar NOT NULL,
  "balance" bigint NOT NULL,
  "status" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);


CREATE TABLE "projects" (
  "id" bigserial PRIMARY KEY,
  "tg_id" bigint NOT NULL,
  "project_name" varchar NOT NULL,
  "key" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX ON "users" ("tg_id");
CREATE INDEX ON "projects" ("tg_id");

INSERT INTO "users" ("tg_id", "username", "balance", "status")
VALUES (727098227, 'example_user', 1000, 'active');

INSERT INTO "projects" ("tg_id", "project_name", "key")
VALUES (727098227, 'MyFirstProject', 'dnahda371631613ndabdhadha361dnabda');
