// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package sqlc

import (
	"context"
)

const checkKeyExist = `-- name: CheckKeyExist :one
SELECT EXISTS (
    SELECT 1 FROM "projects" WHERE "key" = $1
) AS "exists"
`

func (q *Queries) CheckKeyExist(ctx context.Context, key string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkKeyExist, key)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
